version: '3.8'
services:
  api:
    image: yuriydetsyk/icon-lab:${DEPLOY_TAG:-latest}
    container_name: iconlab
    restart: unless-stopped
    build:
      context: ./
      target: production
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - ICONLAB_DB_USERNAME=${ICONLAB_DB_USERNAME:?}
      - ICONLAB_DB_PASSWORD=${ICONLAB_DB_PASSWORD:?}
      - ICONLAB_DB_PORT=${ICONLAB_DB_PORT:?}
      - ICONLAB_SERVER_PORT=${ICONLAB_SERVER_PORT:?}
    ports:
      - ${ICONLAB_SERVER_PORT:-8100}:80
    networks:
      - iconlab_network
    depends_on:
      database:
        condition: service_healthy
