name: IconLab API CI

on:
  push:
    branches: [master, 'release/**']
    paths: ['bd-server/**']
  pull_request:
    branches: [master]
    paths: ['bd-server/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bd-server

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./bd-server/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run test:single
