# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: IconLab App + API CI

on:
  push:
    branches: [ master, 'release/**' ]
  pull_request:
    branches: [ master ]
  # release:
  #   types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./bd-server/package-lock.json
      - run: cd ./bd-client
      - run: npm ci
      - run: npm run lint
      - run: npm run test:single
      - run: cd ../bd-server
      - run: npm ci
      - run: npm run lint
      - run: npm run test:single
