# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: IconLab App CI + CD (STAGE)

on:
  push:
    branches: [ master, 'release/**' ]
    paths: 'bd-client/**'
  pull_request:
    branches: [ master ]
    paths: 'bd-client/**'
  workflow_dispatch:
  # release:
  #   types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bd-client

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./bd-client/package-lock.json
    - name: Install NPM packages
      run: npm ci
    - name: Code linting
      run: npm run lint
    - name: Unit testing
      run: npm run test:single
    - name: Deploy the app
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run deploy:ghp:stage
